#! /bin/bash
#

#$Author: ee364g01 $
#$Date: 2016-08-24 11:16:42 -0400 (Wed, 24 Aug 2016) $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/F16/students/ee364g01/Lab00/Script1 $
#$Revision: 91818 $

Num_Of_Param=$#
Param_Values=$@
echo "The -program received $Num_Of_Param parameters"
echo "The parameters are : "
echo "$Param_Values"
echo "The 2nd parameter is \"$2\""
echo "The 4th parameter is \"$4\""
exit 0
